version: '3'
services:
   nginx:
    image: nginx:latest
    container_name: hw3
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./data/html:/usr/share/nginx/html