version: '3'

services:

  s1:
    build:
      context: .
      dockerfile: Dockerfile1
    ports:
      - 1234:1234
      - 6379:6379

  s2:
    build:
      context: .
      dockerfile: Dockerfile2
    ports:
      - 19092:19092
      - 29092:29092
      - 5678:5678